import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import Navbar from "@/components/shared/Navbar";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "StrategyByte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${openSans.variable} font-OpenSans antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
