import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import "swiper/css";
import Navbar from "@/components/shared/Navbar";
import localFont from "next/font/local";
import Footer from "@/components/shared/Footer";

const chopin = localFont({
  src: [
    {
      path: "../fonts/chopin-font-family/Chopin-Trial-Regular-BF65b1d6917c0ec.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/chopin-font-family/Chopin-Trial-Medium-BF65b1d69162573.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../fonts/chopin-font-family/Chopin-Trial-SemiBold-BF65b1d6917f846.otf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../fonts/chopin-font-family/Chopin-Trial-Bold-BF65b1d691a55be.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-chopin",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "StrategyByte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${openSans.variable} ${chopin.variable} font-OpenSans antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
